export const postConstants = {
    ADD_POST_REQUEST: 'USERS_ADD_POST_REQUEST',
    ADD_POST_SUCCESS: 'USERS_ADD_POST_SUCCESS',
    ADD_POST_FAILURE: 'USERS_ADD_POST_FAILURE',

    DELETE_POST_REQUEST: 'USERS_DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'USERS_DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'USERS_DELETE_POST_FAILURE',

    GETALL_REQUEST: 'USERS_GETALL_POSTS_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_POSTS_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_POSTS_FAILURE',

    GETALL_OWNER_REQUEST: 'USERS_GETALL_OWNER_POSTS_REQUEST',
    GETALL_OWNER_SUCCESS: 'USERS_GETALL_OWNER_POSTS_SUCCESS',
    GETALL_OWNER_FAILURE: 'USERS_GETALL_OWNER_POSTS_FAILURE',

    LIKES_REQUEST: 'USERS_LIKES_REQUEST',
    LIKES_SUCCESS: 'USERS_LIKES_SUCCESS',
    LIKES_FAILURE: 'USERS_LIKES_FAILURE',

    SHARES_REQUEST: 'USERS_SHARES_REQUEST',
    SHARES_SUCCESS: 'USERS_SHARES_SUCCESS',
    SHARES_FAILURE: 'USERS_SHARES_FAILURE',

    GETALL_COMMENTS_REQUEST: 'USERS_GETALL_COMMENTS_REQUEST',
    GETALL_COMMENTS_FAILURE: 'USERS_GETALL_COMMENTS_FAILURE',
    GETALL_COMMENTS_SUCCESS: 'USERS_GETALL_COMMENTS_SUCCESS',

    ADD_COMMENT_REQUEST: 'USERS_ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS: 'USERS_ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'USERS_ADD_COMMENT_FAILURE',

    DELETE_COMMENT_REQUEST: 'USERS_DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_SUCCESS: 'USERS_DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILURE: 'USERS_DELETE_COMMENT_FAILURE',
};
