export const postConstants = {
    ADD_POST_REQUEST: 'USERS_ADD_POST_REQUEST',
    ADD_POST_SUCCESS: 'USERS_ADD_POST_SUCCESS',
    ADD_POST_FAILURE: 'USERS_ADD_POST_FAILURE',

    DELETE_POST_REQUEST: 'USERS_DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'USERS_DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'USERS_DELETE_POST_FAILURE',

    GETALL_POSTS_REQUEST: 'USERS_GETALL_POSTS_REQUEST',
    GETALL_POSTS_SUCCESS: 'USERS_GETALL_POSTS_SUCCESS',
    GETALL_POSTS_FAILURE: 'USERS_GETALL_POSTS_FAILURE',

    LIKES_REQUEST: 'USERS_LIKES_REQUEST',
    LIKES_SUCCESS: 'USERS_LIKES_SUCCESS',
    LIKES_FAILURE: 'USERS_LIKES_FAILURE',

    SHARES_REQUEST: 'USERS_SHARES_REQUEST',
    SHARES_SUCCESS: 'USERS_SHARES_SUCCESS',
    SHARES_FAILURE: 'USERS_SHARES_FAILURE'
};
