export const userConstants = {

    REGISTER_ADD_INFOS_REQUEST: 'ADD_REGISTER_INFOS_REQUEST',
    REGISTER_ADD_INFOS_SUCCESS: 'ADD_REGISTER_INFOS_SUCCESS',
    REGISTER_ADD_INFOS_FAILURE: 'ADD_REGISTER_INFOS_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',


    PUT_REQUEST: 'PUT_REQUEST',
    PUT_SUCCESS: 'PUT_SUCCESS',
    PUT_FAILURE: 'PUT_FAILURE',

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REMOVE_INSPECTED: 'REMOVE_INSPECTED',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    PLAYER_ADD_STATS_REQUEST: 'ADD_STATS_REQUEST',
    PLAYER_ADD_STATS_SUCCESS: 'ADD_STATS_SUCCESS',
    PLAYER_ADD_STATS_FAILURE: 'ADD_STATS_FAILURE',


    USER_PUT_REQUEST: 'USER_PUT_REQUEST',
    USER_PUT_SUCCESS: 'USER_PUT_SUCCESS',
    USER_PUT_FAILURE: 'USER_PUT_FAILURE',

    INSPECT_USER_REQUEST: 'INSPECT_USER_REQUEST',
    INSPECT_USER_SUCCESS: 'INSPECT_USER_SUCCESS',
    INSPECT_USER_FAILURE: 'INSPECT_USER_FAILURE',
};
